import "./globals.css";
// import { Montserrat } from "next/font/google";
import { Open_Sans } from "next/font/google";


// const montserrat = Montserrat({
//   subsets: ["latin"],
//   display: "swap",
//   weight: "600",
// });

const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "600",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        {children}
      </body>
    </html>
  );
}
